### ISSUE TITLE
bwa mem fails on iteration 1

### ISSUE THREAD

**Issue by SethMusker** [faircloth-lab/itero#9]
Hi Brant, I've been running into an error with "itero assemble local" which only occurs after iteration 0 completes successfully, and seems to result from bwa not liking the new "iter-0.all-fasta.fasta" reference. The last few lines of "iter-1.pe.bwa.log" are:
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (758, 1617, 2091)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 4757)
[M::mem_pestat] mean and std.dev: (1480.68, 824.77)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 6090)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 1421646 reads in 135.673 CPU sec, 3.679 real sec
[fputs] Broken pipe

I suspect this may have to do with there being duplicate headers in this fasta as the "iter-1.pe.samtools.log" reads:
[W::sam_hdr_create] Duplicated sequence 'Erica-12927_1_length_1482_cov_559.416839'
[W::sam_hdr_create] Duplicated sequence 'Erica-935_1_length_1785_cov_739.382991'
[E::sam_hrecs_update_hashes] Duplicate entry "Erica-12927_1_length_1482_cov_559.416839" in sam header
samtools view: failed to add PG line to the header

Running itero check binaries returns:
bwa         : 0.7.7-r441
samtools    : 1.10
bedtools    : v2.18.1
spades      : v3.12.0
schwimmbad  : 0.3.0
numpy       : 1.16.5
biopython   : 1.68

I guess an option would be to just append a unique identifier to each header in the new reference fasta, but not being much of a coder I'm not confident enough to implement that without breaking things.

Thanks in advance,
Seth

**Comment by brantfaircloth** [comment]
Ugh.  I think the error probably has to do with the change in an updated version of samtools.  Let me see if I can get the error to pop up in the software tests, and I'll see what i can do about it.

**Comment by SethMusker** [comment]
Thanks for your quick reply! 
I've just realised that I had negelcted to update my conda channels (your bioconda repo was still top) so some of the versions are old. Fixed and reinstalling into a clean environment now and will try again.

**Comment by brantfaircloth** [comment]
Let me know if that fixes it.  It may simply be that downgrading the samtools you use fixes the issues.  I have had success with:

```
→ itero check binaries
bwa         : 0.7.17-r1188
samtools    : 1.8
bedtools    : v2.27.1
spades      : v3.12.0
schwimmbad  : 0.3.0
numpy       : 1.15.4
biopython   : 1.68
```
For the most part, the bedtools, schwimmbad, numpy, and biopython versions should not matter.  BWA really shouldn't matter, either.

**Comment by SethMusker** [comment]
Seems to be working! At least it's on iter-1 and spades is ticking along. Should really have thought to check my environment first...
Anyway, much appreciated.
For the record, these are my versions now:

```
bwa         : 0.7.17-r1188
samtools    : 1.9
bedtools    : v2.29.2
spades      : v3.12.0
schwimmbad  : 0.3.0
numpy       : 1.16.5
biopython   : 1.68
```
And itero is: bioconda/noarch::itero-1.1.2-py_1

**Comment by brantfaircloth** [comment]
Awesome - thanks for tracking down the issue.  And, no worries - glad you got it working and I don't have to dig around and see what's up!
